In [2]:


import pandas as pd
import kagglehub
import os

# Download dataset
path = kagglehub.dataset_download("anvitkumar/shopping-dataset")

print("Dataset Path:", path)

# Show files inside dataset folder
print("\nFiles in dataset folder:")
print(os.listdir(path))

Using Colab cache for faster access to the 'shopping-dataset' dataset.
Dataset Path: /kaggle/input/shopping-dataset

Files in dataset folder:
['lounge-shorts.csv', 'bra.csv', 'ethnic-dresses.csv', 'duffel-bag.csv', 'mangalsutra.csv', 'sunglasses.csv', 'dresses.csv', 'clutches.csv', 'kurta-sets.csv', 'earrings.csv', 'ring.csv', 'clothing-set.csv', 'trunk.csv', 'thermal-bottoms.csv', 'wall-art.csv', 'face-moisturisers.csv', 'belts.csv', 'wallets.csv', 'sweatshirts.csv', 'casual-shoes.csv', 'flip-flops.csv', 'pillow-covers.csv', 'hair-cream-and-mask.csv', 'briefs.csv', 'gloves.csv', 'headphones.csv', 'shirts.csv', 'caps.csv', 'shorts.csv', 'bedsheets.csv', 'co-ords.csv', 'skirts.csv', 'shampoo-and-conditioner.csv', 'runners.csv', 'face-wash-and-cleanser.csv', 'scarves.csv', 'sports-shoes.csv', 'README.md', 'hair-brush-and-comb.csv', 'sherwani.csv', 'saree-blouse.csv', 'foundation.csv', 'home-fragrance-set.csv', 'innerwear-vests.csv', 'sandals.csv', 'candle-holders.csv', 'yoga-mats.csv', 'dinnerware.csv', 'swim-tops.csv', 'lounge-tshirts.csv', 'jeans.csv', 'hair-accessory.csv', 'towel-set.csv', 'lipstick.csv', 'kurtas.csv', 'tunics.csv', 'nightdress.csv', 'lounge-pants.csv', 'bracelet.csv', 'heels.csv', 'outdoor-masks.csv', 'trousers.csv', 'night-suits.csv', 'dupatta.csv', 'tshirts.csv', 'tops.csv', 'tights.csv', 'camisoles.csv', 'curtains-and-sheers.csv', 'bodysuit.csv', 'showpieces.csv', 'table-covers.csv', 'track-pants.csv', 'boots.csv', 'kurtis.csv', 'hair-masks.csv', 'shaving-essentials.csv', 'jackets.csv', 'cutlery.csv', 'jumpsuit.csv', 'backpacks.csv', 'handbags.csv', 'dungarees.csv', 'bathroom-accessories.csv', 'bath-towels.csv', 'trolley-bag.csv', 'floor-mats--dhurries.csv', 'sweaters.csv', 'Combined_dataset.csv', 'mobile-accessories.csv', 'flats.csv', 'formal-shoes.csv', 'bath-robe.csv', 'chair-cover.csv', 'palazzos.csv', 'sarees.csv', 'watches.csv', 'boxers.csv', 'perfume-and-body-mist.csv']

In [3]:
csv_file = os.path.join(path, 'bra.csv')

df = pd.read_csv(csv_file)

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579.0,NaN,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":90,""2_stars"":25,""3_stars"":93,""4_star...",NaN,Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...",NaN,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
1,22063882,GROVERSONS Paris Beauty,Non Padded Cotton Seamless Non-Wired T-shirt Bra,4.0,25,399.0,25.0,"""₹299.00""",INR,http://assets.myntassets.com/assets/images/220...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,Gro███son███ppa█████████Ltd███,"[{""size"":""30B"",""value"":""31.0in"",""value_name"":""...",NaN,"sec███ A-███Plo█████████, I███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
2,19219450,Susie,Black Solid Cotton T-Shirt Bra - Anti-Odour,4.3,12,749.0,50.0,"""₹374.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,GEN███AD ███AIL█████████LIM██████,"[{""size"":""30B"",""value"":""31.0in to 32.0in"",""val...",NaN,2ND███OOR███O 1█████████MAL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
3,22196924,Zivame,Underwired Lightly Padded Pushup Bra,4.3,118,999.0,50.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":6,""2_stars"":7,""3_stars"":8,""4_stars"":...",NaN,MIL███AR ███AIL█████████LIM██████,"[{""size"":""30A"",""value"":""31.0in"",""value_name"":""...",NaN,MIL███TAR███TAI█████████ LI███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
4,19219468,Susie,Women Black Solid Everyday Cotton Bra,4.0,6,699.0,43.0,"""₹398.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,GEN███AD ███AIL█████████LIM██████,"[{""size"":""32B"",""value"":""33.0in to 34.0in"",""val...",NaN,2ND███OOR███O 1█████████MAL███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra

In [6]:
csv_file = os.path.join(path, 'ring.csv')

df = pd.read_csv(csv_file)

In [7]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,15720606,Rubans,Gold-Plated Contemporary Boho Finger Ring,3.5,6,1890.0,74.0,"""₹415.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,AK ███erp███es,"[{""size"":""Onesize""}]",NaN,Plo███o 2███ 4t█████████ast███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ring
1,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995.0,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",NaN,ZAV███ PE███S,"[{""size"":""Onesize""}]",NaN,"12,███T F███R, █████████LDG███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
2,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250.0,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",NaN,NaN,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...","[""rw-16254760_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,15720606,Rubans,Gold-Plated Contemporary Boho Finger Ring,3.5,6,1890.0,74.0,"""₹415.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,AK ███erp███es,"[{""size"":""Onesize""}]",NaN,Plo███o 2███ 4t█████████ast███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ring
1,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995.0,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",NaN,ZAV███ PE███S,"[{""size"":""Onesize""}]",NaN,"12,███T F███R, █████████LDG███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
2,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250.0,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",NaN,NaN,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...","[""rw-16254760_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring

In [10]:
print(df.shape)

(3, 24)

In [11]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [12]:
print(df.dtypes)

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said       float64
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                float64
best_offer                 object
more_offers                object
category                   object
dtype: object

In [13]:
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       3
seller_name               1
sizes                     0
videos                    2
seller_information        1
variations                3
best_offer                0
more_offers               0
category                  0
dtype: int64

In [14]:
df.fillna(0, inplace=True)

In [16]:
print(df.isnull().sum()) ## null and na values removed

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
filtered_df = df[df['rating'] > 4]

In [22]:
print("\nFiltered Rows:")
filtered_df[['title', 'rating' , 'product_description', 'final_price']]

Filtered Rows:

,title,rating,product_description,final_price
1,Zaveri Pearls,4.4,Set of 2 Rose Gold Plated CZ-Studded Contempor...,"""₹359.00"""
2,Zaveri Pearls,4.2,Set Of 3 Gold-Plated White & Green Kundan-Stud...,"""₹2,250.00"""

In [23]:
selected_columns = df[['title', 'rating', 'final_price','seller_name','discount']]

print("\nSelected Columns:")
print(selected_columns.head())

Selected Columns:
           title  rating  final_price     seller_name  discount
0         Rubans     3.5    "₹415.00"  AK ███erp███es      74.0
1  Zaveri Pearls     4.4    "₹359.00"   ZAV███ PE███S      82.0
2  Zaveri Pearls     4.2  "₹2,250.00"               0      81.0

In [24]:
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
)

In [25]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')
df['ratings_count'] = pd.to_numeric(df['ratings_count'], errors='coerce')

In [26]:
df['total_amount'] = df['final_price'] * df['ratings_count']

In [29]:
print("Derived Column ")
print(df[['title', 'total_amount']])

Derived Column
           title  total_amount
0         Rubans           NaN
1  Zaveri Pearls           NaN
2  Zaveri Pearls           NaN

In [30]:
df.to_csv("cleaned_ring_dataset.csv", index=False)

# Summary

- Loaded Combined_dataset.csv using Pandas
- Explored dataset using head(), tail(), shape, columns, and dtypes
- Checked and handled missing values
- Removed duplicate rows
- Filtered products with rating greater than 4
- Selected important columns like title, rating, and final_price
- Created derived column total_amount
- Saved cleaned dataset as cleaned_dataset.csv

In [32]:
# from google.colab import files
# files.download("cleaned_ring_dataset.csv")